"""empty message

Revision ID: 44d53e66aae6
Revises: 7de69b68d496
Create Date: 2019-03-23 18:16:18.203689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44d53e66aae6'
down_revision = '7de69b68d496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TransaksiEvent', 'bandName')
    op.drop_column('TransaksiEvent', 'band_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TransaksiEvent', sa.Column('band_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('TransaksiEvent', sa.Column('bandName', mysql.VARCHAR(length=45), nullable=False))
    # ### end Alembic commands ###
