"""empty message

Revision ID: 7de69b68d496
Revises: 
Create Date: 2019-03-09 03:35:18.398823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de69b68d496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'band', ['bandMail'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'band', type_='unique')
    # ### end Alembic commands ###
